package com.jimi.xhx_agv.entity.model;

import com.jimi.xhx_agv.entity.model.base.BaseAgvLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgvLog extends BaseAgvLog<AgvLog> {
	public static final AgvLog dao = new AgvLog().dao();
}
