package com.jimi.xhx_agv.entity.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("action_log", "id", ActionLog.class);
		arp.addMapping("agv_log", "id", AgvLog.class);
		arp.addMapping("position", "id", Position.class);
		arp.addMapping("server_log", "id", ServerLog.class);
		arp.addMapping("user", "id", User.class);
	}
}

