package com.jimi.xhx_agv.entity.model;

import com.jimi.xhx_agv.entity.model.base.BasePosition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Position extends BasePosition<Position> {
	public static final Position dao = new Position().dao();
}
