package com.jimi.xhx_agv.entity.model;

import com.jimi.xhx_agv.entity.model.base.BaseServerLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ServerLog extends BaseServerLog<ServerLog> {
	public static final ServerLog dao = new ServerLog().dao();
}
