package com.jimi.xhx_agv.entity.model;

import com.jimi.xhx_agv.entity.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
}
