package com.jimi.xhx_agv.entity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePosition<M extends BasePosition<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setHikId(java.lang.String hikId) {
		set("hik_id", hikId);
		return (M)this;
	}
	
	public java.lang.String getHikId() {
		return getStr("hik_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setArea(java.lang.Integer area) {
		set("area", area);
		return (M)this;
	}
	
	public java.lang.Integer getArea() {
		return getInt("area");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setGoodsState(java.lang.Integer goodsState) {
		set("goods_state", goodsState);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsState() {
		return getInt("goods_state");
	}

	public M setLoadGoodTime(java.util.Date loadGoodTime) {
		set("load_good_time", loadGoodTime);
		return (M)this;
	}
	
	public java.util.Date getLoadGoodTime() {
		return get("load_good_time");
	}

	public M setIsLock(java.lang.Boolean isLock) {
		set("is_lock", isLock);
		return (M)this;
	}
	
	public java.lang.Boolean getIsLock() {
		return get("is_lock");
	}

}
