package com.jimi.xhx_agv.entity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePosition<M extends BasePosition<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setHikId(java.lang.String hikId) {
		set("hik_id", hikId);
		return (M)this;
	}
	
	public java.lang.String getHikId() {
		return getStr("hik_id");
	}

	public M setRow(java.lang.Integer row) {
		set("row", row);
		return (M)this;
	}
	
	public java.lang.Integer getRow() {
		return getInt("row");
	}

	public M setCol(java.lang.Integer col) {
		set("col", col);
		return (M)this;
	}
	
	public java.lang.Integer getCol() {
		return getInt("col");
	}

	public M setArea(java.lang.Integer area) {
		set("area", area);
		return (M)this;
	}
	
	public java.lang.Integer getArea() {
		return getInt("area");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setGoodsState(java.lang.Integer goodsState) {
		set("goods_state", goodsState);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsState() {
		return getInt("goods_state");
	}

	public M setLastTransportTime(java.util.Date lastTransportTime) {
		set("last_transport_time", lastTransportTime);
		return (M)this;
	}
	
	public java.util.Date getLastTransportTime() {
		return get("last_transport_time");
	}

	public M setIsLock(java.lang.Boolean isLock) {
		set("is_lock", isLock);
		return (M)this;
	}
	
	public java.lang.Boolean getIsLock() {
		return get("is_lock");
	}

}
